"""Turning an experiment into a job script.

The generated script is meant to be read. If something goes wrong at 2am, you
should be able to ``cat`` it on the cluster and see exactly what ran, in what
environment, with what directives -- no indirection back into slurmherd.

Structure, always in this order:

1. ``#SBATCH`` directives
2. a slurmherd preamble that records the job id and installs an ``EXIT`` trap
   writing the true exit code to a file (the most reliable outcome signal)
3. environment: umask, module purge/load, conda or venv, exports, free-form setup
4. ``cd`` into the working directory
5. the ``pre`` hook
6. your command, wrapped in a function so multi-line commands behave
7. the ``post`` hook, with ``$SLURMHERD_EXIT_CODE`` set
"""

from __future__ import annotations

import shlex
from dataclasses import dataclass
from typing import List, Optional

from .models import Cluster, Experiment, Resources, Site
from .util import format_walltime, parse_walltime

MARKER = "# generated by slurmherd -- edits here are overwritten on the next attempt"


@dataclass(frozen=True)
class RunPaths:
    """Every path an attempt touches on the cluster.

    One directory per experiment holding every attempt, so investigating a run
    means ``cd``-ing to one place and reading files with obvious names.
    """

    run_dir: str
    attempt: int

    @property
    def stem(self) -> str:
        return f"attempt-{self.attempt:03d}"

    @property
    def script(self) -> str:
        return f"{self.run_dir}/{self.stem}.sbatch"

    @property
    def out(self) -> str:
        return f"{self.run_dir}/{self.stem}.out"

    @property
    def err(self) -> str:
        return f"{self.run_dir}/{self.stem}.err"

    @property
    def exit_file(self) -> str:
        return f"{self.run_dir}/{self.stem}.exit"

    @property
    def jobid_file(self) -> str:
        return f"{self.run_dir}/{self.stem}.jobid"

    @property
    def latest_out(self) -> str:
        return f"{self.run_dir}/latest.out"

    @property
    def latest_err(self) -> str:
        return f"{self.run_dir}/latest.err"


def runtime_namespace(paths: RunPaths) -> dict:
    """Values only known once an attempt number exists."""
    return {
        "attempt": paths.attempt,
        "attempt_id": paths.stem,
        "log_out": paths.out,
        "log_err": paths.err,
    }


# --------------------------------------------------------------------------
# #SBATCH directives
# --------------------------------------------------------------------------


def sbatch_directives(
    experiment: Experiment,
    site: Site,
    paths: RunPaths,
    resources: Optional[Resources] = None,
) -> List[str]:
    """Render the ``#SBATCH`` block. Unset fields are simply omitted."""
    res = resources if resources is not None else experiment.resources
    lines: List[str] = [
        f"#SBATCH --job-name={experiment.name}",
        f"#SBATCH --output={paths.out}",
        f"#SBATCH --error={paths.err}",
    ]

    def add(flag: str, value) -> None:
        if value is not None and value != "":
            lines.append(f"#SBATCH --{flag}={value}")

    add("partition", res.partition)
    add("account", res.account)
    add("qos", res.qos)
    add("nodes", res.nodes)
    add("ntasks", res.ntasks)
    add("ntasks-per-node", res.ntasks_per_node)
    add("cpus-per-task", res.cpus_per_task)
    add("mem", res.mem)
    add("mem-per-cpu", res.mem_per_cpu)
    add("mem-per-gpu", res.mem_per_gpu)

    if res.gres:
        add("gres", res.gres)
    elif res.gpus:
        if site.gpu_flag == "gres":
            add("gres", f"gpu:{res.gpus}")
        elif site.gpu_flag == "gpus_per_node":
            add("gpus-per-node", res.gpus)
        else:
            add("gpus", res.gpus)

    add("time", res.time)
    add("constraint", res.constraint)
    add("nodelist", res.nodelist)
    add("exclude", res.exclude)
    if res.exclusive:
        lines.append("#SBATCH --exclusive")
    if res.requeue is not None:
        lines.append("#SBATCH --requeue" if res.requeue else "#SBATCH --no-requeue")

    if experiment.signal:
        sig = experiment.signal
        prefix = "B:" if sig.batch else ""
        lines.append(f"#SBATCH --signal={prefix}{sig.name}@{sig.seconds}")

    notify = experiment.notify
    mail_user = notify.mail_user
    if notify.mail_type:
        lines.append(f"#SBATCH --mail-type={notify.mail_type}")
        if not mail_user and site.mail_domain:
            mail_user = f"{experiment.owner}@{site.mail_domain}" if experiment.owner else None
        if mail_user:
            lines.append(f"#SBATCH --mail-user={mail_user}")

    for raw in res.extra:
        directive = raw if raw.startswith("--") or raw.startswith("-") else f"--{raw}"
        lines.append(f"#SBATCH {directive}")

    return lines


# --------------------------------------------------------------------------
# Environment
# --------------------------------------------------------------------------


def environment_block(experiment: Experiment, site: Site) -> List[str]:
    """Render the module/conda/exports section."""
    env = experiment.env
    lines: List[str] = []

    umask = site.umask
    if umask:
        lines.append(f"umask {umask}")

    if env.purge_modules:
        lines.append("module purge 2>/dev/null || true")
    for module in env.modules:
        lines.append(f"module load {module} 2>/dev/null || module load {module}")

    if env.conda:
        conda_sh = env.conda_sh
        if conda_sh:
            lines += [
                f'if [ -f "{conda_sh}" ]; then',
                f'    . "{conda_sh}"',
                "else",
                "    module load conda 2>/dev/null || true",
                "fi",
            ]
        else:
            lines.append("module load conda 2>/dev/null || true")
        lines.append(f"conda activate {shlex.quote(env.conda)}")

    if env.venv:
        activate = f"{env.venv.rstrip('/')}/bin/activate"
        lines.append(f'. "{activate}"')

    for key, value in env.exports.items():
        lines.append(f"export {key}={shlex.quote(str(value))}")

    if env.setup:
        lines.append("")
        lines.append(env.setup.rstrip())

    return lines


# --------------------------------------------------------------------------
# Whole script
# --------------------------------------------------------------------------


def render_script(
    experiment: Experiment,
    site: Site,
    cluster: Cluster,
    paths: RunPaths,
    command: str,
    project: str = "",
    resources: Optional[Resources] = None,
) -> str:
    """Produce the complete job script for one attempt."""
    res = resources if resources is not None else experiment.resources
    out: List[str] = [f"#!{site.shell}"]
    out += sbatch_directives(experiment, site, paths, res)
    out += [
        "",
        MARKER,
        f"#   experiment : {experiment.name}",
        f"#   cluster    : {cluster.name} ({site.name})",
        f"#   attempt    : {paths.attempt}",
        f"#   project    : {project or '-'}",
        "",
        "SLURMHERD_RUN_DIR=" + shlex.quote(paths.run_dir),
        f"SLURMHERD_ATTEMPT={paths.attempt}",
        "SLURMHERD_EXIT_FILE=" + shlex.quote(paths.exit_file),
        'mkdir -p "$SLURMHERD_RUN_DIR"',
        'rm -f "$SLURMHERD_EXIT_FILE"',
        f'printf "%s\\n" "${{SLURM_JOB_ID:-unknown}}" > {shlex.quote(paths.jobid_file)}',
        f'ln -sfn {shlex.quote(paths.stem + ".out")} {shlex.quote(paths.latest_out)} 2>/dev/null || true',
        f'ln -sfn {shlex.quote(paths.stem + ".err")} {shlex.quote(paths.latest_err)} 2>/dev/null || true',
        "",
        "# The exit file is how slurmherd learns what really happened; the trap",
        "# fires on normal exit and on a trapped SIGTERM at walltime.",
        "__slurmherd_finish() {",
        "    SLURMHERD_EXIT_CODE=${SLURMHERD_EXIT_CODE:-$?}",
        '    printf "%s\\n" "$SLURMHERD_EXIT_CODE" > "$SLURMHERD_EXIT_FILE"',
    ]
    if experiment.hooks.post:
        out += ["    " + line for line in experiment.hooks.post.rstrip().splitlines()]
    out += [
        "    exit $SLURMHERD_EXIT_CODE",
        "}",
        "trap __slurmherd_finish EXIT",
        "trap 'SLURMHERD_EXIT_CODE=143; exit 143' TERM",
        "trap 'SLURMHERD_EXIT_CODE=130; exit 130' INT",
    ]

    if experiment.signal and experiment.hooks.on_signal:
        out += [
            "",
            "__slurmherd_on_signal() {",
        ]
        out += ["    " + line for line in experiment.hooks.on_signal.rstrip().splitlines()]
        out += [
            "}",
            f"trap __slurmherd_on_signal {experiment.signal.name}",
        ]

    env_lines = environment_block(experiment, site)
    if env_lines:
        out += ["", "# --- environment ---"] + env_lines

    if experiment.workdir:
        out += [
            "",
            f"cd {shlex.quote(experiment.workdir)} || {{ echo 'slurmherd: workdir "
            f"{experiment.workdir} is missing' >&2; exit 78; }}",
        ]

    if experiment.hooks.pre:
        out += ["", "# --- pre hook ---", experiment.hooks.pre.rstrip()]

    out += [
        "",
        "# --- command ---",
        "__slurmherd_main() {",
    ]
    out += [line for line in command.rstrip().splitlines()]
    out += ["}", ""]

    if experiment.signal and experiment.hooks.on_signal:
        # Bash only runs a trap between commands, so a foreground job would
        # swallow the warning signal entirely. Backgrounding and waiting is
        # what makes on_signal actually fire.
        out += [
            "__slurmherd_main &",
            "SLURMHERD_CHILD=$!",
            "while true; do",
            '    wait "$SLURMHERD_CHILD"',
            "    SLURMHERD_EXIT_CODE=$?",
            '    if [ "$SLURMHERD_EXIT_CODE" -gt 128 ] && kill -0 "$SLURMHERD_CHILD" 2>/dev/null; then',
            "        continue  # interrupted by a trap, not by the child exiting",
            "    fi",
            "    break",
            "done",
        ]
    else:
        out += ["__slurmherd_main", "SLURMHERD_EXIT_CODE=$?"]

    out += ["", 'exit "$SLURMHERD_EXIT_CODE"', ""]
    return "\n".join(out)


# --------------------------------------------------------------------------
# Validation helpers
# --------------------------------------------------------------------------


def walltime_warning(res: Resources, site: Site) -> Optional[str]:
    """Warn when a requested walltime exceeds the partition's known limit."""
    if not res.time or not res.partition:
        return None
    info = site.partitions.get(res.partition)
    if not info or not info.max_time:
        return None
    requested = parse_walltime(res.time)
    allowed = parse_walltime(info.max_time)
    if requested is None or allowed is None or requested <= allowed:
        return None
    return (
        f"partition {res.partition!r} allows at most {info.max_time} "
        f"but {format_walltime(requested)} was requested -- SLURM will reject this job"
    )
